test:
	nosetests utils

coverage:
	nosetests utils --with-coverage --cover-package=utils

analysis:
	python linear_model_scripts_sub1.py
	python linear_model_scripts_sub2.py
	python linear_model_scripts_sub3.py
	python linear_model_scripts_sub4.py
	python linear_model_scripts_sub5.py
	python linear_model_scripts_sub6.py
	python correlation_analysis_scripts_sub1.py
	python correlation_analysis_scripts_sub2.py
	python correlation_analysis_scripts_sub3.py
	python correlation_analysis_scripts_sub4.py
	python correlation_analysis_scripts_sub5.py
	python correlation_analysis_scripts_sub6.py
	python cross_subject_analysis.py
 
