TITLE="report"

figures:
	cp ../code/images/2d_total_correlation_bar_both_bottle.png ./
	cp ../code/images/2d_total_correlation_bar_both_cat.png ./
	cp ../code/images/2d_total_correlation_bar_both_chair.png ./
	cp ../code/images/2d_total_correlation_bar_both_face.png ./
	cp ../code/images/2d_total_correlation_bar_both_house.png ./
	cp ../code/images/2d_total_correlation_bar_both_scissors.png ./
	cp ../code/images/2d_total_correlation_bar_both_scrambledpix.png ./
	cp ../code/images/2d_total_correlation_bar_both_shoe.png ./
	cp ../code/images/2d_total_correlation_bar_both.png ./
	cp ../code/images/2d_total_correlation_bar_both.png ./
	cp ../code/images/3d_correlation_table_sub001.png ./
	cp ../code/images/3d_non_max_correlation_table_sub001.png ./
	cp ../code/images/3d_total_correlation_bar_both_bottle.png ./
	cp ../code/images/3d_total_correlation_bar_both_cat.png ./
	cp ../code/images/3d_total_correlation_bar_both_chair.png ./
	cp ../code/images/3d_total_correlation_bar_both_face.png ./
	cp ../code/images/3d_total_correlation_bar_both_house.png ./
	cp ../code/images/3d_total_correlation_bar_both_scissors.png ./
	cp ../code/images/3d_total_correlation_bar_both_scrambledpix.png ./
	cp ../code/images/3d_total_correlation_bar_both_shoe.png ./
	cp ../code/images/3d_total_correlation_bar_both.png ./
	cp ../code/images/betas_for_sub001_run001_house.png ./
	cp ../code/images/correlation_table_sub001.png ./
	cp ../code/images/design_matrix_sub001_run001.png ./
	cp ../code/images/non_max_correlation_table_sub001.png ./
	cp ../code/images/sub001_2d_bottle_total_correlation_bar_both.png ./
	cp ../code/images/sub001_2d_cat_total_correlation_bar_both.png ./
	cp ../code/images/sub001_2d_chair_total_correlation_bar_both.png ./
	cp ../code/images/sub001_2d_face_total_correlation_bar_both.png ./
	cp ../code/images/sub001_2d_house_total_correlation_bar_both.png ./
	cp ../code/images/sub001_2d_scissors_total_correlation_bar_both.png ./
	cp ../code/images/sub001_2d_scrambledpix_total_correlation_bar_both.png ./
	cp ../code/images/sub001_2d_shoe_total_correlation_bar_both.png ./
	cp ../code/images/sub001_2d_total_correlation_bar_both.png ./
	cp ../code/images/sub001_3d_bottle_total_correlation_bar_both.png ./
	cp ../code/images/sub001_3d_cat_total_correlation_bar_both.png ./
	cp ../code/images/sub001_3d_chair_total_correlation_bar_both.png ./
	cp ../code/images/sub001_3d_face_total_correlation_bar_both.png ./
	cp ../code/images/sub001_3d_house_total_correlation_bar_both.png ./
	cp ../code/images/sub001_3d_scissors_total_correlation_bar_both.png ./
	cp ../code/images/sub001_3d_scrambledpix_total_correlation_bar_both.png ./
	cp ../code/images/sub001_3d_shoe_total_correlation_bar_both.png ./
	cp ../code/images/sub001_3d_total_correlation_bar_both.png ./
	cp ../code/images/sub001_run_figure_compile.png ./
	cp ../code/images/sub001_run001_bold_prediction.png ./
	cp ../code/images/Task_time_course_sub001_run001.png ./
	cp ../code/images/Try_3D_correlation_sub001.png ./
	cp ../code/images/Volume_RMS_Difference_Outliers_sub001_run001.png ./
	cp ../code/images/subtracted_correlation_table_sub001.png ./
	cp ../code/images/subtracted_correlation_table_sub002.png ./
	cp ../code/images/subtracted_correlation_table_sub003.png ./
	cp ../code/images/subtracted_correlation_table_sub004.png ./
	cp ../code/images/subtracted_correlation_table_sub005.png ./
	cp ../code/images/subtracted_correlation_table_sub006.png ./
	cp ../code/images/AFTS.png ./
	cp ../code/images/sub001_run001_corrFunc.png ./
	cp ../code/images/sub001_run001_residcorrFunc.png ./
	cp ../code/images/sub001_run001_residFit.png ./

all:
	pdflatex $(TITLE).tex
	bibtex $(TITLE)
	pdflatex $(TITLE).tex
	pdflatex $(TITLE).tex
	figures


clean:
	rm -f *.{aux,log,bbl,lof,lot,blg,out}
